### ISSUE TITLE
Another question about dataset split

### ISSUE THREAD

**Issue by depblack** [EndlessSora/DeeperForensics-1.0#11]
Thanks for your interest in our work.
1. Yes. The standard set only includes 1k Youtube videos and 1k manipulated videos (end_to_end).
2. Almost correct. The perturbations with a similar distribution should be applied to the real (1k Youtube videos from ff++, *but no need for 100 actors' videos* since they are source videos used for face manipulation) and fake videos if one would like to train his model on "std+std/sing".

_Originally posted by @EndlessSora in https://github.com/EndlessSora/DeeperForensics-1.0/issues/10#issuecomment-883024042_

**Comment by depblack** [comment]
Sorry for having another similar question to bother you.
Just like【And if one wants to train their model on "std+std/sing"】, if one wants to test their model on just "std/sing", means testing on 5k manipulated videos and what? (I know train:val:test is 7:1:2)

No1. 1k original Youtube videos , test part
No2. 5k Youtube videos (with the same pertubations, e.g. 000_M101.mp4 BW:3 -> 000.mp4 BW:3), test part.
And the "000.mp4" will have 5 manipulated types.
No3. 6k Youtube videos from both No1 and No2, test part
No4. just manipulated videos, no Youtube videos
I guess the answer is No2, right?

**Comment by EndlessSora** [comment]
Yes. The closest answer is No2. And maybe the result of applying perturbations with a similar distribution to a set of corresponding videos would be similar to applying exactly the same perturbation to each video. You are encouraged to try different settings and enrich our benchmark/develop your own benchmark using our dataset.

**Comment by depblack** [comment]
Yes," exactly the same perturbation to each video",  the same as I thought, 

Thank you for reply. 
Good Luck to you!
