### ISSUE TITLE
Script to download them all

### ISSUE THREAD

**Issue by iacopomasi** [EndlessSora/DeeperForensics-1.0#3]
Dear DeeperForensics authors,
great work! Thank you so much. In the effort of seamlessly download automatically all the dataset I create a bash script using `gdown` it worked at the beginning but apparently after a while it brakes with the message for large files only.

```
Access denied with the following error:

        Too many users have viewed or downloaded this file recently. Please
        try accessing the file again later. If the file you are trying to
        access is particularly large or is shared with many people, it may
        take up to 24 hours to be able to view or download the file. If you
        still can't access a file after 24 hours, contact your domain
        administrator. 

You may still be able to access the file from the browser:
```
**Update**: I realized that I was posting the downloading script here which is not correct. @EndlessSora let me know if you want I can share with you the script privately so you can provide it to people that access the dataset

**Comment by EndlessSora** [comment]
Thanks for the great suggestion! Indeed, this issue happens sometimes. You may try to: 1. download it later, and it should work; 2. try other tools like **gdrive** (https://github.com/prasmussen/gdrive).

P.S. I've saved your script from your editing history and cleared the history. First, we will add more suggestions for downloading. Later, we will consider using the script. Thank you!

**Comment by iacopomasi** [comment]
Great! Thank you for clearing the history and for your work!
